### ISSUE TITLE
Update gem on rubygems.org

### ISSUE THREAD

**Issue by yaodong** [ryw/pinboard#20]
Hi, the latest update on rubygems.org is May 2, 2013. Would you update this gem on rubygems.org?

Thanks.

**Comment by badboy** [comment]
Well, I don't seem to have permission to push it. :D

**Comment by ryw** [comment]
@badboy added you as an owner for the gem (badboy@archlinux.us), see if you can push...

**Comment by badboy** [comment]
v1.0.0 published

**Comment by yaodong** [comment]
Thanks guys. :+1:
